### ISSUE TITLE
About the JFreeChart

### ISSUE THREAD

**Issue by ShannonUp** [onclave/NSGA-II#6]
Hello , i download the latest JFreeChart .It is the jcommon-1.0.23 and jfreechart-1.0.19. Most of the import is working well, but the 
"import org.jfree.chart.ui.ApplicationFrame;" keeps saying that "the import cannot be resolved",when i repalce it to"import org.jfree.ui.ApplicationFrame;",it can work well , so i do not know what is the problem.

**Comment by onclave** [comment]
The latest version of JFreeChart is [1.5.1](https://mvnrepository.com/artifact/org.jfree/jfreechart) and that of jCommon is [1.0.24](https://mvnrepository.com/artifact/org.jfree/jcommon). The [POM](https://github.com/onclave/NSGA-II/blob/master/pom.xml) for this project uses JFreeChart at 1.5.0 (1.5.1 should work just fine) and jCommon at 1.0.24. You are using wrong / outdated versions of both which are likely to be incompatible with this library. You can / should use the associated POM file of this project directly to resolve dependency issues.
