### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: org.jfree.chart.ui.ApplicationFrame

### ISSUE THREAD

**Issue by RJoshlan** [onclave/NSGA-II#8]
Hello , i download the JFreeChart .It is the jcommon-1.0.24 and jfreechart-1.5.2. and 5.1 and 5.0 but still i get error for
"import org.jfree.chart.ui.ApplicationFrame;" and it syas caused by class not found, so i don't  know what is the problem. I am using eclipse ide and i also get another issue which is with XYDataset saying class not found similar to application frame error

![Capture](https://user-images.githubusercontent.com/56387693/107042719-f8759c00-67b9-11eb-8076-28d90afa0b6c.PNG)

**Comment by onclave** [comment]
Please provide more information on how you are setting up your project. This is a maven project, hence it can be directly managed by maven to resolve all dependencies.

If you are directly cloning the repository and working on the source code, you need to let Eclipse resolve the dependencies from the [pom.xml](https://github.com/onclave/NSGA-II/blob/master/pom.xml) file. You might need to [import the project as a maven project into Eclipse](https://stackoverflow.com/questions/4869815/importing-a-maven-project-into-eclipse-from-git) before using it.

If you are using this library as a dependency to your  project (recommended) from Maven Central, you can add it as a maven or gradle dependency as described [here](https://mvnrepository.com/artifact/com.debacharya/nsgaii/3.1.3).

In both cases, you do not need to explicitly download any jar files as the IDE will do it for you provided you have an active internet connection.

Also, is this error thrown during build time?

**Comment by RJoshlan** [comment]
Yes this error is thrown during the build time

**Comment by RJoshlan** [comment]
I am setting it up as java project

**Comment by RJoshlan** [comment]
Thanks now i understand. Can you also reply to my other questions

Where do i add the dataset in the code, Its a ddos attack dataset used to conduct feature selection.

and 

secondly

Can i adapt your code for Multi-objective NSGA - 2 for solving feature selection problem, if it does how do i go about it

**Comment by onclave** [comment]
refer issue #9

**Comment by onclave** [comment]
refer issue #7
