### ISSUE TITLE
Can i adapt your code for Multi-objective NSGA - 2 

### ISSUE THREAD

**Issue by RJoshlan** [onclave/NSGA-II#9]
Hi, Your code is really good but Can i adapt your code for Multi-objective NSGA - 2 for solving feature selection problem, if it does how do i go about it

**Comment by onclave** [comment]
NSGA-2, by nature, is a multi-objective optimization algorithm. So, yes, this library can be used for as a MOEA for feature selection.

Unless you require to change the internal working of NSGA-II for your purpose, I suggest you use this library as an external dependency to your project. This library is available on [Maven Central](https://mvnrepository.com/artifact/com.debacharya/nsgaii).

For usage, please go through [Getting Started](https://github.com/onclave/NSGA-II/wiki/Getting-Started), [Introduction](https://github.com/onclave/NSGA-II/wiki/Introduction) and [Documentation](https://github.com/onclave/NSGA-II/wiki/Documentation) section of the wiki. Let me know if you are unable to understand any section.

**Comment by RJoshlan** [comment]
Thanks
